version: '3.7'
services:
  redis:
    image: redis:latest
    networks:
      ms:
        aliases:
          - redis
    ports:
      - 6379:6379
  mysql:
    image: mysql:5.6.45
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      ms:
        aliases:
          - mysql
    ports:
      - 3306:3306
  rmqnamesrv:
    image: foxiswho/rocketmq:server
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - ./rmq/logs:/opt/logs
      - ./rmq/store:/opt/store
    environment:
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-Xms128m -Xmx128m -Xmn128m"
    networks:
      rmq:
        aliases:
          - rmqnamesrv
  rmqbroker:
    image: foxiswho/rocketmq:broker
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
    volumes:
      - ./rmq/logs:/opt/logs
      - ./rmq/store:/opt/store
      - ./rmq/brokerconf/broker.conf:/etc/rocketmq/broker.conf
    environment:
      NAMESRV_ADDR: "rmqnamesrv:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms128m -Xmx128m -Xmn128m"
    command: mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - rmqnamesrv
    networks:
      rmq:
        aliases:
          - rmqbroker
  openresty:
    image: openresty/openresty:latest
    networks:
      ms:
        aliases:
          - openresty
    ports:
      - 8080:80
    # volumes:
    #   - /home/Documents/nginx/conf.d:/etc/nginx/conf.d
networks:
  ms:
    external: true
  rmq:
    name: rmq
    driver: bridge
